#!/usr/bin/env bash
# scaffold-season.sh <year> [base-dir]
# Creates a TaxWiz season working directory with safe permissions.
# base-dir may be a household directory (e.g. ~/tax-prep/parents); default ~/tax-prep.
set -euo pipefail
umask 077   # every file/dir created below is private to the user

YEAR="${1:?usage: scaffold-season.sh <year> [base-dir]}"
BASE="${2:-$HOME/tax-prep}"
[[ "$YEAR" =~ ^20[0-9]{2}$ ]] || { echo "ERROR: year must look like 20XX" >&2; exit 1; }

# Containment: only operate under $HOME, and never inside a git repo we didn't make.
case "$BASE" in
  "$HOME"/*) ;;
  *) echo "ERROR: base-dir must live under \$HOME (got: $BASE)" >&2; exit 1 ;;
esac
if [[ -e "$BASE/.git" ]]; then
  echo "ERROR: $BASE is a git repository — refusing to scaffold tax PII inside a repo" >&2
  exit 1
fi

BASE_EXISTED=false; [[ -d "$BASE" ]] && BASE_EXISTED=true
SEASON="$BASE/$YEAR"
mkdir -p "$SEASON"/{sources,drafts,scratch}
chmod 700 "$SEASON" "$SEASON"/{sources,drafts,scratch}
$BASE_EXISTED || chmod 700 "$BASE"

# Keep the tree out of any index — but never clobber a .gitignore we didn't write.
if [[ -e "$BASE/.gitignore" ]]; then
  grep -qx '\*' "$BASE/.gitignore" || echo "WARN: $BASE/.gitignore exists and doesn't ignore '*' — left untouched; verify it covers this tree" >&2
else
  printf '*\n' > "$BASE/.gitignore"
fi
[[ -e "$BASE/profile.md" ]] || touch "$BASE/profile.md"

for f in source-ledger.md verification-log.md carryforward-ledger.md; do
  [[ -e "$SEASON/$f" ]] || printf '# %s — TY%s\n\n<!-- taxwiz:starter -->\n' "${f%.md}" "$YEAR" > "$SEASON/$f"
done

cat <<EOF
Season directory ready: $SEASON
  sources/   copies of source docs used this season (originals stay where they are)
  drafts/    downloaded draft PDFs from FreeTaxUSA
  scratch/   intermediate extraction output — the ONLY dir cleanse.sh deletes
  data-pack.json / entry-guide.md are generated by the skill, not scaffolded.
Permissions: 700 throughout (umask 077). Gitignored: everything under $BASE.
EOF
