#!/usr/bin/env bash
# scaffold-season.sh <year> [base-dir]
# Creates the TaxWiz season working directory with safe permissions.
set -euo pipefail

YEAR="${1:?usage: scaffold-season.sh <year> [base-dir]}"
BASE="${2:-$HOME/tax-prep}"
[[ "$YEAR" =~ ^20[0-9]{2}$ ]] || { echo "ERROR: year must look like 20XX" >&2; exit 1; }

SEASON="$BASE/$YEAR"
mkdir -p "$SEASON"/{sources,drafts,scratch}
chmod 700 "$BASE" "$SEASON"

# Never let this tree land in a repo or an index.
printf '*\n' > "$BASE/.gitignore"
touch "$BASE/profile.md"

for f in source-ledger.md verification-log.md carryforward-ledger.md; do
  [[ -e "$SEASON/$f" ]] || printf '# %s — TY%s\n\n<!-- taxwiz:starter -->\n' "${f%.md}" "$YEAR" > "$SEASON/$f"
done

cat <<EOF
Season directory ready: $SEASON
  sources/   copies of source docs used this season (originals stay where they are)
  drafts/    downloaded draft PDFs from FreeTaxUSA
  scratch/   intermediate extraction output — the ONLY dir cleanse.sh deletes
  data-pack.json / entry-guide.md are generated by the skill, not scaffolded.
Permissions: 700. Gitignored: everything under $BASE.
EOF
